### ISSUE TITLE
auto detect need for recompile?

### ISSUE THREAD

**Issue by cdriveraus** [stan-dev/rstantools#108]
Well I'm being prodded to switch to using rstantools ;) Currently ctsem has some kind of legacy rstan based setup where changes to the .stan files are detected upon build, and only if they are changed is the c++ recompiled. It seems this functionality isn't in rstantools, unless I miss something? Has anyone reverse engineered it into a package? Though at that point I might lose the apparent benefits of depending on rstantools.

**Comment by andrjohns** [comment]
I'm not sure how much of a benefit this would bring, since the cost of the c++-generation is pretty trivial and is also needed on any change to `rstan` or `StanHeaders`. In terms of distribution, the compiled models can't be shipped with the package source anyway - the package and its models will always be compiled for each platform

**Comment by cdriveraus** [comment]
But in terms of working on the package it's a huge benefit to not have to recompile in order to work with changes to the rest of the software? I'm not talking about the c++ generation but the .dll etc compilation.

**Comment by andrjohns** [comment]
What do you normally use for local development? Once you run `pkgbuild::compile_dll()` does this not still work?

**Comment by cdriveraus** [comment]
I just build all then restart rstudio --- the whole point is to avoid compiling the dll if I've only made changes to the .R files. Sorry if I'm missing something.

**Comment by cdriveraus** [comment]
ok. but I have to keep track of it in my head and then use a different command. I'll see how annoying it is :)
