### ISSUE TITLE
devtools::install in step-by-step instructions fails (missing/empty \title field)

### ISSUE THREAD

**Issue by sieste** [stan-dev/rstantools#25]
Following the step-by-step guide, I get an error on 

```r
devtools::install(local=FALSE)
```

```
# [... lots of C++ compiler output ...]
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
Error in Rd_info(db[[i]]) : 
  missing/empty \title field in '/tmp/RtmpfIoONs/R.INSTALL2e133c949d42/rstanlm/man/date.Rd'
Rd files must have a non-empty \title.
See chapter 'Writing R documentation' in manual 'Writing R Extensions'.
* removing ‘/home/stefan/lib/R/rstanlm’
Error: Command failed (1)
```

Contrary, `devtools::load_all(recompile=TRUE)` (which is what the vignette does internally) is successful.

**Comment by sieste** [comment]
Oops, that was my fault. I have a custom `date` function defined in my `.Rprofile` which is automatically in the global environment, and so the package skeleton function assumed `date` is part of the package. So following the guide from an `R --vanilla` session works fine. Sorry about that.

 (I think this error is why I initialised the dummy environment in the first version of the vignette.)

But I might not be the only person to run into this. Is there any way to prevent objects from the global environment to be included in the package? Or to explicitly initialize the package skeleton with a completely empty environment (which seems like the reasonable default behavior)?

As a simple fix, the vignette could start with a `rm(list=ls())` to clean the environment first.

**Comment by jgabry** [comment]
Pulling from the global environment is what we did so as to not break with what utils::package.skeleton does, but this behavior of package.skeleton is definitely a headache so I’d be happy to go ahead and change this (we can just pass a dummy environment to package.skeleton). @bgoodri any objection?

In fact at some point I think we should probably switch to calling devtools::create (if I recall the function name correctly) instead of package.skeleton.
