### ISSUE TITLE
Confusing SOURCES in makevars.win

### ISSUE THREAD

**Issue by dmenne** [stan-dev/rstantools#33]
Makevars in the default skeleton now simplifies inclusion of sources:

`SOURCES = $(wildcard stan_files/*.stan)`

but the corresponding line in Makevars.win is highly confusing:

`SOURCES = stan_files/bernoulli.stan stan_files/binomial.stan stan_files/continuous.stan stan_files/count.stan stan_files/jm.stan stan_files/lm.stan stan_files/mvmer.stan stan_files/polr.stan`

Leftover of some test versions?

**Comment by jgabry** [comment]
@dmenne Yeah looks like it. Thanks for reporting that! 

@bgoodri I assume we should just be using the same `SOURCES = $(wildcard stan_files/*.stan)` line in both Makevars files, or is there some reason for hardcoding it in Makevars.win?

**Comment by dmenne** [comment]
Slightly aside: will CRAN accept the NOTE when using the GNU requirement? I asked CRAN admin about it, but did not get a response.

**Comment by bgoodri** [comment]
Fixed in https://github.com/stan-dev/rstanarm/commit/ebd07a9c7af01322d9b25a9af4c96f54f71765e4 

Yes, CRAN should tolerate that NOTE. It means that they have to use GNU make on Solaris, but Stan only halfway works on Solaris anyway. If you don't have that many models, you could hard-code the paths to the Stan programs in both Makevars and Makevars.win but you would have to update them every time you add a Stan program or change its filename.
